### ISSUE TITLE
Update Svelte Auth UI to use stitches

### ISSUE THREAD

**Issue by silentworks** [supabase/auth-ui#100]
The Svelte auth-ui library is currently doing its own thing when handling CSS. On this project we decided to use [stitches](https://stitches.dev/) so that the styles can be shared across libraries.

**Comment by nileshtrivedi** [comment]
Wait.. there's a Svelte auth-ui library? Where?

- Supabase only has [auth-helpers](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit) for Svelte Kit.
- [This third-party project](https://github.com/supabase-community/supabase-ui-svelte) hasn't seen any commits in almost 18 months.

**Comment by silentworks** [comment]
Yes this was just released recently but do note this works in the client only. It's not a server side form package.

**Comment by nileshtrivedi** [comment]
@silentworks Can you please share a link to repo or docs? Or did you mean [this](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit)?
