### ISSUE TITLE
Google logo loads as a big image for a split second at load

### ISSUE THREAD

**Issue by tomasroaldsnes** [supabase/auth-ui#101]
# Bug report

## Describe the bug

With Google provider enabled, the Google logo is huge for a split second when loading the view.

## To Reproduce

Loading this view.
`<Auth
            supabaseClient={supabase}
            appearance={{
              theme: ThemeSupa,
              variables: {
                default: {
                  colors: {
                    brand: "#3d808c",
                    brandAccent: "#2c5b63",
                  },
                },
              },
            }}
            providers={["google"]}
            magicLink
            localization={{
              variables: {
                sign_in: {
                  email_label: "Din epostadresse",
                  password_label: "Ditt passord",
                  email_input_placeholder: "Epost",
                  password_input_placeholder: "Passord",
                  social_provider_text: "Logg inn med",
                  button_label: "Logg inn",
                  link_text: "Har du allerede en konto? Logg inn",
                },
                sign_up: {
                  email_label: "Din epostadresse",
                  password_label: "Ditt passord",
                  email_input_placeholder: "Epost",
                  password_input_placeholder: "Passord",
                  social_provider_text: "Logg inn med",
                  button_label: "Opprett konto",
                  link_text: "Har du ikke en konto? Opprett konto",
                },
                magic_link: {
                  email_label: "Din epostadresse",
                  email_input_placeholder: "Epost",
                  button_label: "Send innloggingslenke på epost",
                  link_text: "Logg inn uten passord",
                },
                forgotten_password: {
                  email_label: "Din epostadresse",
                  password_label: "Ditt passord",
                  email_input_placeholder: "Epost",
                  button_label: "Send meg nytt possord på epost",
                  link_text: "Har du glemt passordet?",
                },
                update_password: {
                  password_label: "Nytt passord",
                  password_input_placeholder: "Ditt nye passord",
                  button_label: "Oppdater passordet",
                },
              },
            }}
          />`

## Expected behavior

Not seeing a huge Google logo when loading the view.

## System information

All devices

**Comment by tomasroaldsnes** [comment]
I think I found the problem. 
`
<svg class="c-eSSyNk" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="512px" height="512px"><path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path><path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path><path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path><path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path></svg>
`

Width and height for button image are set as 512px.

**Comment by tomasroaldsnes** [comment]
https://github.com/supabase/auth-ui/blob/main/packages/react/src/components/Auth/Icons.tsx#L14-L15
These should be changed to actual sizes.

**Comment by avgupta456** [comment]
I am also running into this problem. Did you find a temporary fix?

**Comment by rdylina** [comment]
Came here to report this very issue.

**Comment by bookvacuum** [comment]
experiencing the same issue

**Comment by silentworks** [comment]
A fix was submitted by @rdylina that got released in version `0.3.5` for `auth-ui-react`.
