### ISSUE TITLE
Port for react package

### ISSUE THREAD

**Issue by KunwarVSuryavanshi** [supabase/auth-ui#104]
# Bug report

## Describe the bug

While running the pnpm dev command in the top most folder, unable to find the dev port for react package

## To Reproduce

Running pnpm dev in root folder.

## Expected behavior

If I am not wrong then like sevlte and solid we should also have port for react, to see the changes made live.
## Screenshots
![image](https://user-images.githubusercontent.com/35609032/215856242-ff81edf3-5b46-4caf-b616-2378ae26de75.png)

## System information

- OS:  Windows
- Browser (if applies) chrome
- Version of Node.js: v16.18.1

## Additional context

Wanted to implement HCaptcha in Auth-ui-react.

**Comment by silentworks** [comment]
React app runs in storybook. The others are developed in their application framework hence them having a port. Run `pnpm storybook:react` for the react version.

**Comment by silentworks** [comment]
This now has an example app similar to the other packages.
