### ISSUE TITLE
How about stating that there is not yet a UI component for password resets?

### ISSUE THREAD

**Issue by hiroshinishio** [supabase/auth-ui#105]
Why not specify that there is not yet a UI component for password resets? If it is not there, I will have to make it myself, and then I will be able to make up my mind. If I don't know if it's there or not, I'll have to seek it out...

**Comment by Hallidayo** [comment]
Hi @hiroshinishio - I can add something in the [Auth-UI] (https://supabase.com/docs/guides/auth/auth-helpers/auth-ui) section in the docs on the current support views?

**Comment by Hallidayo** [comment]
Hi @hiroshinishio - I've just created a pull for this issue to show the views currently supported in the docs.
