### ISSUE TITLE
Problem in repo for @supabase/auth-ui-svelte

### ISSUE THREAD

**Issue by vivasvan1** [supabase/auth-ui#156]
# In [@supabase/auth-ui-svelte](https://www.npmjs.com/package/@supabase/auth-ui-svelte?activeTab=readme) forgot password form incorrect field type.

## Forgot password link is a email failed. which wont let users submit until an `@` is added to password

I was aware this is not the correct repo but was unable to find the github repo for [@supabase/auth-ui-svelte](https://www.npmjs.com/package/@supabase/auth-ui-svelte?activeTab=readme) so posting it here.

## To Reproduce

[Follow these steps](https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit) 

and replace the Auth with username password
```
<Auth
      supabaseClient={data.supabase}
      magicLink={true}
      redirectTo={`${data.url}/logging-in?redirect=/`}
      appearance={{ theme: ThemeSupa, style: { input: 'color: #fff' } }}
/>
```

## Expected behavior
password to be of type="password"

## Screenshots
![image](https://user-images.githubusercontent.com/21074796/223995351-77031cfc-fd32-49e9-b35e-49d5aa337ff1.png)
![image](https://user-images.githubusercontent.com/21074796/223997263-c867a3de-4770-407f-9827-6889f4b24ba5.png)

## System information

- OS: Linux
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by silentworks** [comment]
This should now be fixed in release `0.1.5`.
