### ISSUE TITLE
Using builtin Auth form and magic link without filling in email results in invalid error message

### ISSUE THREAD

**Issue by huksley** [supabase/auth-ui#179]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

It writes "unsupported_otp_type" when I click "Send magic link" without filling an e-mail.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/huksley/supabase-auth-nextjs
2. Put into .env.local your Supabase project NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY
3. npm run dev
4. Open http://localhost:3000 
5. Auth form appears
6. Select [Send a magic link email](http://localhost:3000/#auth-magic-link)
7. Press button **Send Magic Link**
8. Error appears

## Expected behavior

Button either disabled or a valid error message, such as "Please fill in your e-mail" are displayed.

## Screenshots

https://github.com/supabase/auth-ui/assets/1594349/733579f8-6e3a-4626-b17a-9da38b6a8116

## System information

- OS: MacOS 13.3.1
- Browser: Chrome 113
- Version of Node.js: v16.20.0
- Relevant modules versions:
```
    "@supabase/auth-helpers-nextjs": "^0.6.1",
    "@supabase/auth-helpers-react": "^0.3.1",
    "@supabase/auth-ui-react": "^0.4.2",
    "@supabase/auth-ui-shared": "^0.1.6",
    "next": "^12.2.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
```

## Additional context

Maybe relevant: https://github.com/orgs/supabase/discussions/6238

**Comment by cokeposada** [comment]
Same issue :(
