### ISSUE TITLE
Email / password not hidable

### ISSUE THREAD

**Issue by accesstechnology-mike** [supabase/auth-ui#180]
Within an app _requiring_ social login, it's not possible through view types to hide email / password options. 

Expected behaviour view="social" would display social login options only.

![image](https://github.com/supabase/auth-ui/assets/55278705/d3f021fd-389d-4969-a90a-075c4c220770)

**Comment by silentworks** [comment]
You can hide email and password by using the `onlyThirdPartyProviders={true}`.
