### ISSUE TITLE
Additional documentation required to get examples up and running

### ISSUE THREAD

**Issue by jeremypeters** [supabase/auth-ui#200]
# Improve documentation

## Describe the problem

No documentation on how to get the examples up and running. 

I wanted to get the Svelte example running locally - these are the issues I have had that could have been avoided with some documentation:

1/ `$ npm i` gave the following error:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

Ok, I've never experienced this error before, or used workspaces. After having a Google I found a suggestion to use a different package manager - ah wait, yep, there's a couple of `pnpm` files in the root. I installed that and use that, and errors are gone. I'm guessing that `pnpm install` needs to be run in the root as well as the example project.

2/ Running `$ npm i` from the Svelte project root gave the error `Internal server error: supabaseUrl is required.` Ok, makes sense, added Supabase local development info.

3/ Then running `$ npm i` again gave the error `Internal server error: Failed to resolve entry for package "@supabase/auth-ui-svelte". The package may have incorrect main/module/exports specified in its package.json`.

Given up at this point and am moving on.

## Describe the improvement

Basic documentation required for running the example projects.

**Comment by silentworks** [comment]
The examples in this repo are used for developing the package and should never be used outside of this package as their only intent is to be used in this package. We have a link in the readme to the [development.md](https://github.com/supabase/auth-ui/blob/main/development.md) which states how to use this repo.
