### ISSUE TITLE
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'crypto.subtle.digest') in SocialAuth.svelte

### ISSUE THREAD

**Issue by brunobely** [supabase/auth-ui#206]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`window.crypto.subtle` is (sometimes?) [`undefined` in mobile Safari](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2543#issuecomment-721854162), resulting in an error when trying to use social providers. In my production app, deployed on Vercel, things work as expected. In development mode, though, the following error is thrown:

`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'crypto.subtle.digest'): SocialAuth.svelte:21:85`

I can't find any instances of `crypto.subtle` in @supabase/auth-ui, maybe it's one of its dependencies?

**Comment by silentworks** [comment]
As that [issue you linked](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2543#issuecomment-721854162) to stated that iOS 10.2 and below doesn't support the standard `SubtleCrypto` which is what the `@supabase/supabase-js` library uses. You will have to use a polyfill in your project to get it working as we don't support non-standard crypto libraries.

**Comment by brunobely** [comment]
This still happens on iOS 16.6, so the OS version doesn't seem to be the issue.
