### ISSUE TITLE
Hide sign up link

### ISSUE THREAD

**Issue by cdedreuille** [supabase/auth-ui#47]
It would be great to be able to hide the sign-up link. In our case, our app is closed in beta and we just don't want people to sign up.

**Comment by kennethcassel** [comment]
+1 on this, would be nice to be able to use this in a flow where someone has to first purchase a subscription / access before sign-up.

**Comment by bobmolgui** [comment]
+1

**Comment by silentworks** [comment]
This is now possible with the latest release by passing a `showLinks={false}` prop to the component.

```jsx
<Auth
  supabaseClient={supabase}
  view="sign_in"
  showLinks={false}
/>
```

This now means if you are using something like NextJS, you can just show the view of the component you wish on each page without worrying about the component using its internal state to change to the signup page. Do note however that this is just a visual change so if a user knows how to pass state into an component using the React dev tools for instance they could show the `sign_up` view by passing that to the `view` prop.

**Comment by jtlapp** [comment]
I must be missing something. I was able to create users until I switched over to using `view="sign_in"` and `view="sign_up"`. After splitting sign in and sign up, sign up sends the following invalid request:

```
POST http://localhost:54321/auth/v1/token?grant_type=password

{ "email": "myemail@gmail.com", "password": "mypassword", "gotrue_meta_security": {} }
```

This returns status 400 (bad request) with payload, `{ "error": "invalid_grant", "error_description": "Invalid login credentials" }`.

Meanwhile, the functioning sign-in submits a user object.

What am I doing wrong?

**Comment by silentworks** [comment]
@jtlapp you gave me a scare there as I just noticed the original message in my inbox. Thanks for coming back and stating what the issue was.

**Comment by WesselKoorn** [comment]
In my case I wanted to hide the signup link but didn't want to get rid of the magic and forgot password links. I solved it with custom styling:

```
<Auth
  supabaseClient={supabaseClient}
  providers={[]}
  magicLink={true}
  appearance={{
     theme: ThemeSupa,
     className: {
      anchor: styles.anchor,
     },
  }}
/>
```

Scss module:
```
.anchor {
  &:nth-child(3) {
    display: none;
  }
}
```
