### ISSUE TITLE
Is this how it is suppose to look like when you first add it to a NextJs page?

### ISSUE THREAD

**Issue by cdedreuille** [supabase/auth-ui#48]
I'm pretty sure this will be solved when there's a concrete example of how to use it but when you first set it up, this is what you get 👇 which is far from close to the video demo you shared. It seems that there's still quite a lot of styling to add outside the component like giving a maxWidth, add a title, ...

![CleanShot_2022-10-18_at_10 41 55](https://user-images.githubusercontent.com/1540635/196417968-09e52046-6fde-4b1d-b8ec-177a4801d833.png)

**Comment by silentworks** [comment]
This is how it should look. What you saw in the video was with user preference customization. Maybe we should create an example in this repo with that kind of customization. If you go to this page https://supabase.com/auth and scroll to the bottom you should see the demo you saw in the video, you can inspect and copy the surrounding code to customize yours the same.

**Comment by silentworks** [comment]
The examples in this repo has similar customization as that of the example on the Supabase website. You can check it out and use it in your own code.
