### ISSUE TITLE
Support custom components

### ISSUE THREAD

**Issue by The-Code-Monkey** [supabase/auth-ui#56]
# Feature request

## Is your feature request related to a problem? Please describe.

I don't want to have to use the inbuilt styles and components built by you (no offence).

I want to be able to pass a custom button component, form, and input.

## Describe the solution you'd like

Maybe an overrides or components object could be passed that would be used instead of the ones already in place

## Describe alternatives you've considered

I've tried my own for but for some reason it just doesn't work correctly, plus it would be nice to use the inbuilt logic of this package without having to re write it just to have custom elements

**Comment by david-plugge** [comment]
Have you considered creating a custom ui from scratch?

**Comment by The-Code-Monkey** [comment]
@david-plugge I have but I thought if I can have the functional code pre done and I don't have to think about it. There is less to manage

**Comment by silentworks** [comment]
This is out of scope and not the purpose of this library. As @david-plugge stated you are better off creating your own library to work with your setup.
