### ISSUE TITLE
Got `ReferenceError: merge is not defined` when deployed to Vercel with NextJS 13

### ISSUE THREAD

**Issue by laubonghaudoi** [supabase/auth-ui#65]
# Bug report

I am using @supabase/auth-ui-react with Nextjs 13, and when I deployed my app to Vercel and went to the auth page, it gave me an client-side error like the screenshot shows below. `Application error: a client-side exception has occurred (see the browser console for more information).` 

I got no error when developing locally with `yarn dev`, and no error when `yarn build` either. It only occurs when deployed to Vercel. Is this a bug related to Webpack?

## Screenshots

![image](https://user-images.githubusercontent.com/11172180/200186451-64271f35-5e76-4c65-afbe-454539a4f724.png)
![image](https://user-images.githubusercontent.com/11172180/200186475-e55c1ae9-593a-40b4-8f1e-0f3d10395880.png)

I clicked into the file prompted by the last line of error `at MessagePort.T (framework-3b5a00d5d7e8d93b.js:33:1904)` and it seems like Webpack-related.

![image](https://user-images.githubusercontent.com/11172180/200186680-f20fae7d-bc17-44b3-972b-9c2c7322bdb2.png)

## System information

- OS: Windows 11
- Browser: Edge
- Version of supabase-js: latest
- Version of Node.js: 18.12.0

**Comment by silentworks** [comment]
You probably have a outdated lock file. Update your lock file and try again, also are you able to replicate this locally? It would be good if you could provide a minimal repo with this issue so I can test it locally and deploy to vercel to see this too.

**Comment by laubonghaudoi** [comment]
Hi @silentworks , yes I have updated my `yarn.lock` file but the issue still persists. I just created a minimal repo: 
https://github.com/laubonghaudoi/supabase-auth-bug/tree/main

I deployed it to vercel using my supabase db. Here is the root url: https://supabase-auth-bug.vercel.app/

And when I go to https://supabase-auth-bug.vercel.app/account which is the auth ui, it gave the same error:
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/11172180/200414747-ac695692-a6f5-4f94-8ce6-8a5dd645eb8c.png">

I suspect that this is a Next 13 related. Because I didn't have this issue when I was using Next 12. This happened only after I migrated to Next 13.

**Comment by nkeat12** [comment]
Any updates here?

**Comment by sagarchoudhary96** [comment]
https://github.com/supabase/auth-ui/issues/45 this just-merge package is the one causing this i reverted to previous version where it was using lodash and it works fine :)

**Comment by laubonghaudoi** [comment]
Hi @sagarchoudhary96 , do you mean that this is fixed by https://github.com/supabase/auth-ui/pull/57 ? Hope there can be a new release soon.

**Comment by sagarchoudhary96** [comment]
yes, it works with that. i will try to raise a PR to fix the same.

**Comment by laubonghaudoi** [comment]
Just upgraded and verified that the error is gone. Thanks!
