### ISSUE TITLE
Impossible to setup redirectTo for signup action in email confirmation

### ISSUE THREAD

**Issue by jibay** [supabase/auth-ui#72]
# Bug report

## Describe the bug

Impossible to setup redirectTo for signup action in email confirmation

## To Reproduce

Use this code:

```
<Auth
					
  supabaseClient={supabase}
  redirectTo={"http://localhost:3001/app/login"}
  appearance={{ theme: ThemeSupa }}
  theme="dark" 

/>

```

## Expected behavior

In the case of signup i have this bad url on email confirmation:

http://localhost:8000/auth/v1/verify?token=3b5354ca745399152ae8e25808ca51a7514fff1f70599d0e3db9c31e&type=signup&redirect_to=http://localhost:3001/

I would like to have this url:

http://localhost:8000/auth/v1/verify?token=3b5354ca745399152ae8e25808ca51a7514fff1f70599d0e3db9c31e&type=signup&redirect_to=http://localhost:3001/app/login

In the case of recovery i have the right url on recovery email

http://localhost:8000/auth/v1/verify?token=dd5c6a230f2013250d4e945d1fb56dcb893e65dbe999b758d8f4f3b0&type=recovery&redirect_to=http://localhost:3001/app/login

Thank you for your help

**Comment by surajondev** [comment]
Hey @jibay, I have the same issue. Do you find any solution?
