### ISSUE TITLE
SVG icons with invalid React DOM attributes

### ISSUE THREAD

**Issue by beauja** [supabase/auth-ui#74]
# Bug report

## Describe the bug

There are SVG elements within [Icons.tsx](https://github.com/supabase/auth-ui/blob/main/packages/react/src/components/Auth/Icons.tsx) that have invalid React DOM attribute names. These invalid names cause React to emit a warning when these SVG elements are used. I received these warnings when using the Azure provider.

## To Reproduce

Use the [Auth component](https://github.com/supabase/auth-ui/blob/main/packages/react/src/components/Auth/Auth.tsx) with either the `azure`, `bitbucket` or `notion` providers

```JSX
import { createClient } from '@supabase/supabase-js';
import { Auth } from '@supabase/auth-ui-react';

const supabase = createClient('<INSERT PROJECT URL>', '<INSERT PROJECT ANON API KEY>');

const App = () => <Auth supabaseClient={supabase} providers={['azure', 'bitbucket', 'notion']}/>;
```

## Expected behavior

All occurences of the HTML attributes  `clip-rule`, `fill-rule`, `stop-color` and `stop-opacity` within [Icons.tsx](https://github.com/supabase/auth-ui/blob/main/packages/react/src/components/Auth/Icons.tsx) should be camel-cased, as specfied by the [React docs](https://reactjs.org/docs/dom-elements.html).

## System information

- OS: Windows
- Browser: Chrome
- Version of @supabase/supabase-js: 2.1.0
- Version of @supabase/auth-ui-react: 0.2.6
- Version of Node.js: 19.0.1

**Comment by beauja** [comment]
Opened a PR #75 with a fix.

**Comment by silentworks** [comment]
PR merged and will be included in the next release.
