### ISSUE TITLE
Request to add providers property to Auth UI docs

### ISSUE THREAD

**Issue by donovangomez** [supabase/auth-ui#80]
# Property for Third Party Providers

## Link 
 [Legacy Auth component](https://ui.supabase.io/components/auth).
[Current Auth UI component](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui)

## Describe the problem
Definitely could be user error on my part, but I couldn't find anything for third party providers in the current docs. I went back to the legacy component and used `providers={['google', 'facebook', 'github']}` Not sure if it was mentioned anywhere else but it would be nice to know the option was there. <3

**Comment by Hallidayo** [comment]
Hi @donovangomez - I've created a pull on the supabase repo for this.

**Comment by donovangomez** [comment]
@Hallidayo Just saw it got added thanks!
