### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by psteinroe** [supabase/auth-ui#81]
## Chore

This package will probably be driven by the community a lot. To not frustrate contributors, it would be great to have a more immediate release cycle. As an example, I added the locales two weeks back and it has not been released yet. The release should be either instant with every PR or at least twice a week.

**Comment by silentworks** [comment]
This is because locales won't be part of this repo as they will make the package size too big. I will create a roadmap soon to outline what the package will look like going forward.
