### ISSUE TITLE
Sign in with scopes (e.g. Spotify)

### ISSUE THREAD

**Issue by strangecarr** [supabase/auth-ui#82]
Hi, in the supabse auth docs, it says you can request scopes if needing additional data from an OAuth provider.
https://supabase.com/docs/reference/javascript/v1/auth-signin

[edit: have successfully used this method by making my own spotify login button, but wondering if it's possible to do via Auth-UI]

The example is for github, but am assuming similar for other providers.

I am using Spotify and would like to utilise the web player sdk and need some additional scopes for my app (e.g. to stream music if the user has a spotify premium account from within the app). 

How can these be requested using the auth-ui component?

**Comment by silentworks** [comment]
This has been added in the latest release and more information on how to use it can be found in this other issue until we write the docs for it. https://github.com/supabase/auth-ui/issues/102#issuecomment-1533354014
