### ISSUE TITLE
The appearance prop of Auth component throw exception when it's undefined

### ISSUE THREAD

**Issue by giladtamam** [supabase/auth-ui#85]
# Bug report

Clicking on 'Set object' of appearance prop on Auth storybook throw exception
on line number 117 `appearance?.theme[theme]` should be fixed to `appearance?.theme?.[theme]`

## To Reproduce

1. Go to default  Auth story
2. Click on 'Set object' of appearance prop on controls tab

## Expected behavior
Error should not be thrown when clicking on 'Set object' of appearance

## Screenshots

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/4085945/206924886-8dedc8c0-0819-4475-9e95-d62378888cea.png">

## System information
OS: macOS
Browser: chrome
Version of supabase-js: 2.0.0-rc.7
Version of Node.js: v16.18.1

**Comment by silentworks** [comment]
Storybook removed from this project and this is no longer a bug.
