### ISSUE TITLE
Custom CSS classes

### ISSUE THREAD

**Issue by emersonlaurentino** [supabase/auth-ui#94]
I want to use Tailwind for customization, but I can't because the Button component has a default style and the `generateClassNames` always will concat if the customization, in my case overwriting.

https://github.com/supabase/auth-ui/blob/76ca3e8de4b3ed28f3b6dd21beca7fc8f7315419/packages/react/src/components/UI/Button.tsx#L63

I believe the lines of this comment are important to avoid this case.

https://github.com/supabase/auth-ui/blob/76ca3e8de4b3ed28f3b6dd21beca7fc8f7315419/packages/react/common/theming/utils.ts#L41-L46

**Comment by ultracodez** [comment]
Any updates?

**Comment by ultracodez** [comment]
Might be related to [#17](https://github.com/supabase/ui/issues/17)

**Comment by silentworks** [comment]
This has been fixed in the latest release with this PR https://github.com/supabase/auth-ui/pull/146.

You can now just add `extend: false` to the `appearance` property to not have any default styles rendered.

```tsx
<Auth 
  supabaseClient={supabaseClient} 
  appearance={{ 
    extend: false, 
    className: {
      container: 'space-y-2'
    } 
  }}
/>
```
